<h1>Cache / Logs</h1>

<div style="max-height: 400px; overflow-y: auto">
	<table align="left">
		<thead>
			<tr>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($logs as $log):
			preg_match('#--([\d]{4}-[\d]{2}-[\d]{2})--([\d]{2}-[\d]{2})#', $log->getBaseName(), $matches);
		?>
			<tr>
				<td><?php echo $matches[1] . ' ' . $matches[2]; ?></td>
				<td>
					<a href="<?php echo $this->link(['wch-log' => $log->getBaseName()]); ?>">Delete</a>
					<a href="<?php echo $this->link(['wch-log-show' => $log->getBaseName()]) ?>">Show</a>
				</td>
			</tr>
		<?php endforeach; ?>
			<tr>
				<td></td>
				<td><a href="<?php echo $this->link(['wch-log-all' => 'yes']); ?>">Delete all</a></td>
			</tr>
		</tbody>
	</table>
	<table style="margin-left: 5px" align="right">
		<thead>
			<tr>
				<th>Name</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($cache as $row): ?>
				<tr>
					<td><?php echo $row->getBaseName(); ?></td>
					<td><a href="<?php echo $this->link(['wch-cache' => $row->getBaseName()]) ?>">Truncate</a></td>
				</tr>
			<?php endforeach; ?>
			<tr>
				<th colspan="2">Files</th>
			</tr>
			<?php foreach ($files as $row): ?>
				<tr>
					<td><?php echo $row->getBaseName(); ?></td>
					<td><a href="<?php echo $this->link(['wch-cache-file' => $row->getBaseName()]) ?>">Truncate</a></td>
				</tr>
			<?php endforeach; ?>
			<tr>
				<th colspan="2">Actions</th>
			</tr>
				<tr>
					<td></td>
					<td><a href="<?php echo $this->link(['wch-cache-all' => 'yes']) ?>">Truncate all</a></td>
				</tr>
		</tbody>
	</table>
</div>
